version: '3.8'

services:
  fluentd:
    image: fluent/fluentd:edge
    user: root
    volumes:
    - ./config:/fluentd/etc/
    - ./app:/fluentd/log/files/
    - ./output:/output/

  app:
    image: alpine
    volumes:
      - ./app:/app
    command: [ "/bin/sh", "-c", "chmod +x /app/app.sh && ./app/app.sh" ]
