version: '3.8'

services:
  fluentd:
    build: .
    user: root
    volumes:
    - ./config:/fluentd/etc/
    - ./app:/fluentd/log/files/
    - ./output:/output/
    environment:
      LOKI_URL: http://loki:3100
      LOKI_USERNAME:
      LOKI_PASSWORD:

  loki:
    image: grafana/loki
    ports: 
      - 3100:3100

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
    - ./loki_datasource.yaml:/etc/grafana/provisioning/datasources/loki_datasource.yaml

  app:
    build: ./app/.
    volumes:
      - ./app:/app
    command: [ "bundle", "exec", "ruby", "./app.rb" ]
