version: '3.8'

services:
  fluentd:
    image: fluent/fluentd:edge
    user: root
    volumes:
    - ./config:/fluentd/etc/
    - ./app:/fluentd/log/files/
    - ./output:/output/
    environment:
    - FLUENTD_NAME="my-sinatra-app"
    - FLUENTD_HOST="fluentd"
    - FLUENTD_PORT=24224

  app:
    build: ./app/.
    ports: 
      - 4567:4567
    volumes:
      - ./app:/app
    command: [ "bundle", "exec", "rackup", "-p", "4567", "--host", "0.0.0.0"  ]
